### ISSUE TITLE
Problèmes de contraste

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#10]
Dark Memariani :

![contraste 1](https://github.com/x-yzt/psychonaut/assets/72821408/f51e769b-6bc8-469a-b8a9-23841822dfc9)

![contraste 2](https://github.com/x-yzt/psychonaut/assets/72821408/0554f985-59c1-428a-9504-835193639099)

![contraste 3](https://github.com/x-yzt/psychonaut/assets/72821408/06483413-06d7-4742-ae3e-1ff987c1a968)

**Comment by x-yzt** [comment]
Pour des raisons techniques, un nouveau thème sombre est en préparation, notamment pour résoudre ces problèmes de contraste. Il s'appelle `Datura`, c'est dispo dans le machin pour sélectionner les thèmes dans le footer.

Ça ne sert a rien de relever les soucis de contraste pour le moment, par contre ce sera précieux quand le truc sera plus avancé.

**Comment by x-yzt** [comment]
S'il y a des problèmes de contraste avec Datura ou Crystal Meth, c'est de nouveau pertinent de les signaler ici.

**Comment by Tridimensionnel** [comment]
Datura :

![image](https://github.com/x-yzt/psychonaut/assets/72821408/05fd4dc3-efa2-4e16-917f-6d0a22bbdf99)

![image](https://github.com/x-yzt/psychonaut/assets/72821408/81c30012-f18c-453e-a0f1-7ff8205cacfc)

![image](https://github.com/x-yzt/psychonaut/assets/72821408/0bf65d3c-3dad-43f7-96f0-85874c8a1a09)
(-> pseudos invisibles depuis newest members)

**Comment by x-yzt** [comment]
Bien vu. Les deux derniers sont réglés, le premier je n'arrive pas à trouver où c'est ?

**Comment by Tridimensionnel** [comment]
C'est partout en haut de chaque sous-forum, mais on peut le supprimer en une fois, essaye avec un compte poubelle

**Comment by Tridimensionnel** [comment]
précision : même problème avec le bandeau qui apparaît sur desktop pour demander l'autorisation de notifications push

**Comment by x-yzt** [comment]
terminado

**Comment by Tridimensionnel** [comment]
Je ne peux pas réouvrir, mais les titres des aperçus de profils ne sont pas réglés :)

![image](https://github.com/x-yzt/psychonaut/assets/72821408/1fe82114-b604-4706-b40e-0ae5fcf166e6)
