### ISSUE TITLE
Balises taille de texte

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#16]
Dans [ce topic](https://www.psychonaut.fr/threads/mes-experiences-au-butane-cest-long.34040), on constate une incompatibilité des balises de taille de texte

EDIT : et fonts aussi

**Comment by Snapyou2** [comment]
Pas trop galère à faire pour les tailles de police via l'éditeur de BBcode custom sur le portail admin d'XF en soi si jamais : https://www.psychonaut.fr/admin.php?bb-codes/
Je devrais pouvoir m'en occuper d'ici chépakan

**Comment by Tridimensionnel** [comment]
Pas le même problème, mais le titre correspond toujours : les balises de texte ne fonctionnent pas.

Exemple : https://www.psychonaut.fr/threads/juste-pour-dire.21868/post-651523

J'ai mis "taille 1" et ça sort normal.

**Comment by Snapyou2** [comment]
Problème résolu, il y avait une balise custom [size] legacy qui foutait la merde, dans l'admin panel. Mais du coup ça bloque maintenant pour les balises [size=small] vu que xenforo ne prend que les chiffres. Je vais faire une query SQL pour changer les [size=small] en [size=1], ça sera plus clean.

**Comment by Tridimensionnel** [comment]
Chouette ! Je laisse l'issue ouverte ?

**Comment by Snapyou2** [comment]
Du coup tu peux fermer l'issue ui
