### ISSUE TITLE
Bug ajout image topic feature

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#20]
Quand j'édite un thread pour rajouter une image dans l'option "promote to feature"

![image](https://github.com/x-yzt/psychonaut/assets/72821408/974d1cb1-a31d-4552-a4e2-80ae31a24724)

**Comment by x-yzt** [comment]
c'est un composant interne de xenfo qui est en cause, il y a pas grand chose qu'on puisse faire à part attendre un fix de leur part :/

**Comment by Tridimensionnel** [comment]
Du coup je ferme :)
