### ISSUE TITLE
désactiver animations

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#21]
Salut, est-ce qu'on pourrait désactiver l'animation d'apparition progressive des topics (et autres apparentées) ? C'est en fait plutôt irritant quand on se déplace rapidement sur le forum, notamment pendant les tâches documentalistes

**Comment by x-yzt** [comment]
comme le machin prévu pour désactiver ça marche pas bien, j'ai bricolé un truc, et tant qu'à faire au lieu de tout retirer j'ai juste mis un gros coup de turbo à cette anim
j'ai l'impression que ça va, si c'est pas le cas tu peux réouvrir l'issue
