### ISSUE TITLE
Bug d'encodage

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#23]
Petit problème d'apostrophes sur d'anciens topics : elles sont remplacées par un élégant `&#8217;`

Exemple : https://www.psychonaut.fr/threads/nouveau-ici-hey-jeune-psychow-fais-gaffe-a-ton-dos-protege-tes-abdos.28196/

**Comment by Snapyou2** [comment]
Uhm je pourrais modifier directement les strings `&#8217;` par des apostrophes dans la BDD, c'est trop galère à faire en soi.

**Comment by Tridimensionnel** [comment]
c'est trop galère ou pas trop galère ?

**Comment by x-yzt** [comment]
Exécuter cette requête sur la DB de prod devrait le faire :

```sql
UPDATE `xf_post` SET `message` = replace(message, '&#8217;', '\'')
```

je ne veux pas tout casser a lors je laisse @Snapyou2 le faire avec une sauvegarde avant ! (ou m'expliquer comment marchent les nouvelles sauvegardes)

**Comment by Snapyou2** [comment]
Après quelques galères sur phpmyadmin (il kiffait pas le code pour les apostrophes apparemment), on est bon je crois.
Mais chelou j'avais jamais vu ce truc.
```
 #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''&#8217)' at line 1
```
