### ISSUE TITLE
des liens cassés :<

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#25]
Il y a encore des vieux liens ne marchent plus :(

Par exemple, dans [ce post](https://www.psychonaut.fr/threads/welcome-5-apb.15992/post-321641), il y a un lien sous cette forme : http://www.psychonaut.com/post-41915.html?f=97&start=75
Ça sort l'erreur suivante : "The requested page could not be found. (Code: invalid_route, controller: -, action: -)"

Dans [ce post](https://www.psychonaut.fr/threads/5-apb-et-6-apb-impressions.22015/post-449779), il y a un lien sous cette forme :
https://www.psychonaut.fr/rcs/46119-5-apb-entre-le-bien-et-le-mal.html
Même erreur.

Dans [ce post](https://www.psychonaut.fr/threads/welcome-5-apb.15992/post-321667) il y a ce lien : 
psychonaut.com/post-35934-303550.html?f=27
CloudFlare me sort un Timeout.

**Comment by x-yzt** [comment]
J'ai l'impression que ces liens sont des liens qui datent vraiment, genre de l'époque vbulletin. Même au cas par cas, je ne suis pas capable de comprendre à quel sujet pointaient ces liens, car ils utilisent des identifiants de posts qui ont été perdus au cours des migrations passées.

Malheureusement je crois qu'il n'y a rien a faire :(
