### ISSUE TITLE
Réparer la balise [ref]

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#3]
Ou mieux ! Exemple :

![ref](https://github.com/x-yzt/psychonaut/assets/72821408/c8671364-8d1f-4ccc-839e-e8c534c7675e)

`
[code]La dernière page d'Internet[ref]https://www.dernierepage.com/[/ref][/code]`

**Comment by x-yzt** [comment]
La balise `[ref]` est ""réparée"", mais malheureusement, lors de l'importation, Xenforo a décidé d'utiliser l'auto-liaison et les intégrations sur les liens à l'intérieur des balises `[ref]` existantes, ce qui a transformé les pages l'utilisant en une soupe de balises monumentale

C'est compliqué de faire un outil automatisé pour gérer ça, le plus rapide que j'ai trouvé c'est copier coller le contenu du post dans un éditeur de texte et y aller à grands coups de find and replace.

Je l'ai fait sur la fiche proto par exemple, en remplaçant en gros :

- `[ref][URL]` ➡️ `[ref]`
- `[/ref][/URL]` ➡️ `[/ref]`
- `[MEDIA=reddit]` ➡️ `https://www.reddit.com/r/`
- `[/MEDIA]` ➡️ ``

Et même avec ces règles il faut repasser à la main derrière pour corriger les trucs bizarres. Et il y a des chances que chaque post soit un peu un cas particulier...

**Comment by x-yzt** [comment]
Je viens d'y penser, mais si ça concerne peu de longs messages (et il me semble que c'est le cas) on peut tout simplement réimporter le contenu de ces messages depuis l'ancienne base SQL.

Si vous faites une liste des identifiants de sujets (le nombre à la fin des URLs de sujets), je peux m'en charger.

Je laisse l'issue ouverte pour le moment, du coup.

**Comment by Tridimensionnel** [comment]
> Si vous faites une liste des identifiants de sujets (le nombre à la fin des URLs de sujets), je peux m'en charger.

Faut d'abord que je refasse les redirections, du coup, puisque les deux problèmes concernent typiquement les mêmes topics

**Comment by Tridimensionnel** [comment]
Fiche info 2C-B : 32554
Fiche info LSD : 32877
MDMA et complément alimentaire : 32619

On est d'accord que ça ne réparera pas les tableaux ?

**Comment by Tridimensionnel** [comment]
Abandonné
