### ISSUE TITLE
Mise en avant, sur les profils, des messages populaires

### ISSUE THREAD

**Issue by Tridimensionnel** [x-yzt/psychonaut#6]
cf xyzt :

"J'aimais bien le truc "message le plus liké" du profil de l'ancien forum. On peut rajouter ce message dans "À propos" ou même mieux, ajouter un onglet complet dans le profil (genre : Dernières activités / Derniers messages / Meilleurs messages / À propos)"

**Comment by Snapyou2** [comment]
J'ai checké des plugins, il n'y a rien de similaire developpé pour XF malheureusement. Donc faudrait en faire un et j'ai pas les skills ni le temps pour les apprendre en ce moment, sorry. Peut-être dans très longtemps ou sinon faudrait engager un dév pour faire ça (ou s'en battre les couilles, c'est pas super utile comme fonctionnalité).
